

import Footer from '../components/Footer'
import Navbar from '../components/Navbar'
import './globals.css'

export const metadata = {
  title: 'PokeNext',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="pt-br">
      <body>
        <Navbar />
        <main className='min-h-[70vh]'>{children}</main>
        <Footer />
      </body>
    </html>
  )
}
